### ISSUE TITLE
[BUG] - Cards with a colon in its name aren't outputted properly

### ISSUE THREAD

**Issue by lukegothic** [MrTeferi/MTG-Proxyshop#51] opened 2022-11-10 07:15 UTC
**Describe the bug**
The process of saving the output fails when a rendered card has a colon in its name. An empty file with name from the beggining of the card name to the colon is generated instead.

**To Reproduce**
1. Put an art image named Circle of Protection Red.jpg insithe the art folder
2. Open proxyshop and render

**Your system:**
 - Python version: 3.10.4
 - Windows version: 10
 - Photoshop version: 2021
 - Proxyshop: 1.1.8

**Screenshots**
![image](https://user-images.githubusercontent.com/3224037/201024626-7628a8fb-ff1d-4aa0-80ca-3038eee9b98c.png)

**Comment by HelixVita** [comment] 2022-11-10 07:39
Duplicate of https://github.com/MrTeferi/MTG-Proxyshop/issues/23

@lukegothic I believe this is fixed in 1.1.9, you should update to that version.

**Comment by lukegothic** [comment] 2022-11-10 07:43
Good to know, but I'm not yet able to use 1.1.9 because of #48

**Comment by MrTeferi** [comment] 2022-11-11 13:05
Has already been fixed

**Closed by MrTeferi** 2022-11-11 13:05 UTC
Labels: bug
