### ISSUE TITLE
Curse of the Bronze Tablet - "Skip Failed Cards" doesn't help

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#14] opened 2022-07-10 02:53 UTC
**Describe the bug**
Certain cards, such as [[Bronze Tablet]], cause MTG-Proxyshop to fail to render in such a way that all subsequent cards also fail to render.

**To Reproduce**
Simply attempt to render one of the problem cards. The ones I've found so far are: 
- Bronze Tablet (Tom Wänerstrand) [ATQ]
- Giant Oyster (Nicola Leonard) [HML]
- Cooperation (Phil Foglio) [ICE]

If you do "Render Target" it will simply fail.

If you do "Render All" (on some arbitrary collection of art files which includes one of these problem cards), then those cards will render fine until Proxyshop reaches the problem card. It'll fail the same way, but then it will also proceed fail on every subsequent card. I.e. the "Skip Failed Cards" option does not protect against this kind of failure.

_Additional observations:_
- Both Photoshop AND the Proxyshop GUI _must_ be closed and re-started, else all cards will continue failing (even the non-problem cards).
- Photoshop cannot be closed normally. Must end task using Task Manager.
- Task manager reveals Photoshop is using a large amount of memory
- Error in python terminal output says something about zero division error

**Your system:**
Note: I first encountered this using my "Ancient" template on my forked version of Proxyshop, so to be sure it wasn't just an issue with my setup I went ahead and reproduced the issue using a clean version of Proxyshop in a brand new virtual python env.
- Proxyshop Template: "Normal"
- Proxyshop version: Freshly cloned from main branch: https://github.com/MrTeferi/MTG-Proxyshop/commit/bebd79e6a273b9135e80561f585297464c3d15d9
- Python version: 3.9 (Fresh virtual python environment with only the packages from requirements.txt)
- Windows version: Windows 11
- Photoshop version: 2022 latest

**Screenshots**
This gif was captured when I first encountered the problem:

![BronzeTabletIsCursed](https://user-images.githubusercontent.com/102387379/178129608-959b9f28-abfa-4a35-a8f2-3edd824b47e7.gif)

**Comment by MrTeferi** [comment] 2022-07-10 04:17
Problem definitely caused by #9 as we sussed out on Discord, most likely fixed in next release but will add these cards to the list in the tracker for issue 9.  Case closed :)

**Closed by MrTeferi** 2022-07-10 04:17 UTC
